<a href="https://colab.research.google.com/github/subham129/Deep-learning/blob/main/Word_Embedding_Using_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd


In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
voc_size = 10000

In [4]:
onehot = [one_hot(words,voc_size)for words in sent]
print(onehot)

[[3567, 6414, 4118, 8582], [3567, 6414, 4118, 2826], [3567, 9207, 4118, 6762], [6645, 4760, 7661, 5567, 1441], [6645, 4760, 7661, 5567, 3507], [9271, 3567, 3137, 4118, 7353], [9434, 1052, 3735, 5567]]


In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
sent_length = 8
embedded_docs = pad_sequences(onehot,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3567 6414 4118 8582]
 [   0    0    0    0 3567 6414 4118 2826]
 [   0    0    0    0 3567 9207 4118 6762]
 [   0    0    0 6645 4760 7661 5567 1441]
 [   0    0    0 6645 4760 7661 5567 3507]
 [   0    0    0 9271 3567 3137 4118 7353]
 [   0    0    0    0 9434 1052 3735 5567]]


In [8]:
dim = 15

In [11]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step
[[[-0.01811717  0.00660273 -0.04815933 -0.01967493 -0.04851807
    0.0239916   0.01511247  0.02416498  0.04382301 -0.03082821]
  [-0.01811717  0.00660273 -0.04815933 -0.01967493 -0.04851807
    0.0239916   0.01511247  0.02416498  0.04382301 -0.03082821]
  [-0.01811717  0.00660273 -0.04815933 -0.01967493 -0.04851807
    0.0239916   0.01511247  0.02416498  0.04382301 -0.03082821]
  [-0.01811717  0.00660273 -0.04815933 -0.01967493 -0.04851807
    0.0239916   0.01511247  0.02416498  0.04382301 -0.03082821]
  [-0.03298662  0.011736   -0.02091867 -0.04670198 -0.02181046
   -0.01862645 -0.0344106   0.0431358  -0.01883929 -0.00993609]
  [ 0.00579742  0.04103235 -0.02625045 -0.04723469 -0.04228787
   -0.01988744 -0.0470088   0.04107079  0.03466416 -0.03151121]
  [-0.03109905  0.02889282 -0.00074389 -0.0298479   0.01224996
    0.0357019  -0.04711256 -0.00179449 -0.00275054 -0.00703736]
  [-0.00538699 -0.02314491  0.04908587 -0.01430888  0.0161807
   -0.0424

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 3567, 6414, 4118, 8582], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[-0.01811717  0.00660273 -0.04815933 -0.01967493 -0.04851807  0.0239916
   0.01511247  0.02416498  0.04382301 -0.03082821]
 [-0.01811717  0.00660273 -0.04815933 -0.01967493 -0.04851807  0.0239916
   0.01511247  0.02416498  0.04382301 -0.03082821]
 [-0.01811717  0.00660273 -0.04815933 -0.01967493 -0.04851807  0.0239916
   0.01511247  0.02416498  0.04382301 -0.03082821]
 [-0.01811717  0.00660273 -0.04815933 -0.01967493 -0.04851807  0.0239916
   0.01511247  0.02416498  0.04382301 -0.03082821]
 [-0.03298662  0.011736   -0.02091867 -0.04670198 -0.02181046 -0.01862645
  -0.0344106   0.0431358  -0.01883929 -0.00993609]
 [ 0.00579742  0.04103235 -0.02625045 -0.04723469 -0.04228787 -0.01988744
  -0.0470088   0.04107079  0.03466416 -0.03151121]
 [-0.03109905  0.02889282 -0.00074389 -0.0298479   0.01224996  0.0357019
  -0.04711256 -0.00179449 -0.00275054 -0.00703736]
 [-0.00538699 -0.02314491  0.04908587 -0.01430888  0.0161807  -0.04243617
  -0.03355417 -0.0